### ISSUE TITLE
TypeError: run_cfa() got an unexpected keyword argument 'get_synt_labels'

### ISSUE THREAD

**Issue by luoxyhappy** [DorianJoubaud/CounterFactualAugmentation-CFA-#1]
when I run the example in readme.md. it occurs.

**Comment by DorianJoubaud** [comment]
Hello, thank you for raising this issue. Error should be fixed, please pull last version and try again.
 `get_synt_labels` now correctly provides an additional array with labels {0, 1} to distinguish between original and synthetic data. You can find an example in the notebook cfaExample.ipynb.

**Comment by luoxyhappy** [comment]
Thanks a lot!
