### ISSUE TITLE
It seems that it does not generate instances.

### ISSUE THREAD

**Issue by luoxyhappy** [DorianJoubaud/CounterFactualAugmentation-CFA-#2]
when i run the example in readme, there is an error in the sentence: "return np.concatenate((X, synthetic_instances)), np.concatenate((y, np.ones(np.array(synthetic_instances).shape[0])))":ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s). And I print the synthetic_instances to find that it is an empty list.

**Comment by DorianJoubaud** [comment]
Hello, thank you for your return. Problem was that fixed values of fd and tol end up by creating no possible synthetic data.
Problem is solved with new simple example in the Readme + returning initial dataset (as well as a print to warn the user) when condition on hyperparameter cannot lead to create synthetic data.
